kind: Pod
apiVersion: v1
metadata:
  name: airflow-pod
  labels:
    app: airflow
spec:
  containers:
    - &airflow
      name: airflow-scheduler
      command: [ 'airflow', 'scheduler' ]
      image: neoman36/myairflow:latest
      env:
        - name: AIRFLOW_HOME
          value: '/root/airflow'
        - name: AIRFLOW__CORE__SQL_ALCHEMY_CONN
          value: 'postgresql+psycopg2://airflow:airflow@postgres-service:5432/airflow'
        - name: AIRFLOW__CORE__DAGS_FOLDER
          value: '/root/airflow/dags'
        - name: AIRFLOW__CORE__BASE_LOGS_FOLDER
          value: '/root/airflow/logs'
      volumeMounts:
        - mountPath: /root/airflow/dags
          name: airflow-dags
        - mountPath: /root/airflow/logs
          name: airflow-logs
        - name: airflow-config
          readOnly: true
          mountPath: /root/airflow/airflow.cfg
          subPath: airflow.cfg
    - <<: *airflow
      name: airflow-webserver
      ports:
        - containerPort: 80
      command: [
          'airflow', 'webserver',
          '-p', '80',
      ]
  volumes:
    - name: airflow-dags
      persistentVolumeClaim:
        claimName: airflow-dags-pvc
    - name: airflow-logs
      persistentVolumeClaim:
        claimName: airflow-logs-pvc
    - name: airflow-config
      configMap:
        name: airflow-configmap
        defaultMode: 420
  nodeSelector:
    "kubernetes.io/hostname": minikube
