kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: airflow-dags-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  resources:
    requests:
      storage: 100Mi
  selector:
    matchLabels:
      files: dags
