apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-logs
  labels:
    files: logs
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    server: 10.0.2.2
    path: /home/vpetrov/h/airflow/airflow-data/logs
