kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: postgres-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: slow
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      files: pg_data
