apiVersion: v1
kind: PersistentVolume
metadata:
  name: fileshare
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  nfs:
    server: 10.0.2.2
    path: /mnt/sharedfolder
